name: ASP.NET Web Forms CI

on:
  push:
    branches:
      - client-sided-conversion
  pull_request:
    branches:
      - client-sided-conversion

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: List files in the repository
      run: dir

    - name: Install NuGet
      run: nuget restore "Web Project/Web Project.sln"

    - name: Build solution
      run: |
        "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\MSBuild\\Current\\Bin\\MSBuild.exe" "Web Project\\Web Project.sln" /p:Configuration=Release

    - name: Run tests
      run: |
        "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\Common7\\IDE\\Extensions\\TestPlatform\\vstest.console.exe" "**\\*Tests.dll"
      continue-on-error: true
