name: ASP.NET Web Forms CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install NuGet
      run: nuget restore MySolution.sln

    - name: Build solution
      run: msbuild MySolution.sln /p:Configuration=Release

    - name: Run tests
      run: |
        "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" **\*Tests.dll
      continue-on-error: true
